services:
  node1:
    image: ghcr.io/bromq-dev/vibemq:latest
    build:
      context: ../..
    ports:
      - 1883:1883

  node2:
    image: ghcr.io/bromq-dev/vibemq:latest
    build:
      context: ../..
    ports:
      - 1884:1883
    volumes:
      - ./node2.toml:/etc/vibemq/config.toml:ro
    depends_on:
      - node1
    
    
