[auth]
allow_anonymous = true

[[bridge]]
name = "node1"
address = "node1:1883"
protocol = "mqtt"
client_id = "node2-bridge"
enabled = true
loop_prevention = "no_local"

[[bridge.forwards]]
local_topic = "#"
remote_topic = "#"
direction = "both"
retain = true
qos = 1
